# Generated by Django 4.0.3 on 2023-02-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'Stories'},
        ),
        migrations.RemoveField(
            model_name='story',
            name='content',
        ),
        migrations.AlterField(
            model_name='story',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
