# Generated by Django 4.0.3 on 2023-04-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_alter_story_options_story_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(blank=True, help_text='optional', null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(help_text='required', max_length=512),
        ),
        migrations.AlterField(
            model_name='story',
            name='url',
            field=models.URLField(blank=True, help_text='optional', null=True),
        ),
    ]
