# Generated by Django 4.0.3 on 2023-04-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('UPVOTE', 'Upvote'), ('DOWNVOTE', 'Downvote')], max_length=20),
        ),
    ]
