# Generated by Django 4.0.3 on 2023-04-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_notification_from_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='object_type',
            field=models.CharField(default='story', max_length=255),
            preserve_default=False,
        ),
    ]
